spring:
  application:
    name: shop-manager-web
  profiles:
    active:
      - dev
  reids:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1

server:
  port: 8092

#dubbo配置
dubbo:
  registries:
    protocol: zookeeper
    address: 127.0.0.1:2181
  consumer:
    timeout: 100000
    check: false
  application:
    name: ${spring.application.name}
